//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vending.Model.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineDrinks
    {
        public int Id { get; set; }
        public int IdMachine { get; set; }
        public int IdDrink { get; set; }
        public int Count { get; set; }
    
        public virtual Drinks Drinks { get; set; }
        public virtual Machines Machines { get; set; }
    }
}
