//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vending.Model.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VendingEntities : DbContext
    {
        public VendingEntities()
            : base("name=VendingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Coins> Coins { get; set; }
        public virtual DbSet<Drinks> Drinks { get; set; }
        public virtual DbSet<MachineCoins> MachineCoins { get; set; }
        public virtual DbSet<MachineDrinks> MachineDrinks { get; set; }
        public virtual DbSet<Machines> Machines { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
